// src/components/ArticlePreview.jsx
import React from 'react'
import { Link } from 'react-router-dom'

function ArticlePreview({ article }) {
  return (
    <div className="article-preview" key={article.slug}>
      <div className="article-meta">
        <Link to={`/profile/${article.author.username}`}>
          <img src={article.author.image} alt="Author avatar" />
        </Link>
        <div className="info">
          <Link to={`/profile/${article.author.username}`} className="author">
            {article.author.username}
          </Link>
          <span className="date">{article.createdAt}</span>
        </div>
        <button type="button" className="btn btn-outline-primary btn-sm pull-xs-right">
          <i className="ion-heart" /> {article.favoritesCount}
        </button>
      </div>
      <Link to={`/article/${article.slug}`} className="preview-link">
        <h1>{article.title}</h1>
        <p>{article.body}</p>
        <span>Read more...</span>
        <ul className="tag-list">
          {article.tagList.map((tag) => (
            <li key={tag} className="tag-default tag-pill tag-outline">
              {tag}
            </li>
          ))}
        </ul>
      </Link>
    </div>
  )
}

export default ArticlePreview

// src/components/Article/ArticlePreview.tsx
import { For } from "solid-js";
import NavLink from "../NavBar/NavLink";

const FAVORITED_CLASS = "btn btn-sm btn-primary";
const NOT_FAVORITED_CLASS = "btn btn-sm btn-outline-primary";

export default (props) => {
  const {
    title,
    description,
    slug,
    createdAt,
    tagList,
    author: { username, image },
  } = props.article;

  return (
    <div class="article-preview">
      <div class="article-meta">
        <NavLink href={`/@${username}`} route="/profile">
          <img src={image} alt="" />
        </NavLink>

        <div class="info">
          <NavLink class="author" href={`/@${username}`} route="/profile">
            {username}
          </NavLink>
          <span
            class="date"
            textContent={/*@once*/ new Date(createdAt).toDateString()}
          />
        </div>

        {props.token && (
          <div class="pull-xs-right">
            <button
              class={
                props.article.favorited ? FAVORITED_CLASS : NOT_FAVORITED_CLASS
              }
              onClick={[props.onClickFavorite, props.article]}
            >
              <i class="ion-heart" /> {props.article.favoritesCount}
            </button>
          </div>
        )}
      </div>

      <NavLink href={`article/${slug}`} route="/article" class="preview-link">
        <h1>{title}</h1>
        <p>{description}</p>
        <span>Read more...</span>
        <ul class="tag-list">
          <For each={tagList}>
            {(tag) => (
              <li class="tag-default tag-pill tag-outline" textContent={tag} />
            )}
          </For>
        </ul>
      </NavLink>
    </div>
  );
};
