// src/components/footer/footer.tsx
import { component$, Host } from "@builder.io/qwik";

export default component$(
  () => {
    return (
      <Host>
        <div class="container">
          <a href="/" class="logo-font">
            conduit
          </a>
          <span class="attribution">
            An interactive learning project from{" "}
            <a href="https://thinkster.io">Thinkster</a>. Code &amp; design
            licensed under MIT.
          </span>
        </div>
      </Host>
    );
  },
  {
    tagName: "footer",
  }
);

// apps/conduit/src/app/components/footer/footer.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooterComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<footer>
  <div class="container">
    <a href="/" class="logo-font">conduit</a>
    <span class="attribution">
      An interactive learning project from
      <a href="https://thinkster.io">Thinkster</a>. Code &amp; design licensed
      under MIT.
    </span>
  </div>
</footer>
