// src/components/Article/ArticleList.tsx
import { For, Show, Suspense } from 'solid-js'
import { useStore } from '../../store'
import ArticlePreview from './ArticlePreview'

export default (props) => {
	const [{ token }, { unmakeFavorite, makeFavorite }] = useStore(),
		handleClickFavorite = (article, e) => {
			e.preventDefault()
			article.favorited ? unmakeFavorite(article.slug) : makeFavorite(article.slug)
		},
		handlePage = (v, e) => {
			e.preventDefault()
			props.onSetPage(v)
			setTimeout(() => window.scrollTo(0, 0), 200)
		}
	return (
		<Suspense fallback={<div class='article-preview'>Loading articles...</div>}>
			<For
				each={props.articles}
				fallback={<div class='article-preview'>No articles are here... yet.</div>}
			>
				{(article) => (
					<ArticlePreview article={article} token={token} onClickFavorite={handleClickFavorite} />
				)}
			</For>
			<Show when={props.totalPagesCount > 1}>
				<nav>
					<ul class='pagination'>
						<For each={[...Array(props.totalPagesCount).keys()]}>
							{(v) => (
								<li
									class='page-item'
									classList={{ active: props.currentPage === v }}
									onClick={[handlePage, v]}
								>
									<a class='page-link' href='' textContent={v + 1} />
								</li>
							)}
						</For>
					</ul>
				</nav>
			</Show>
		</Suspense>
	)
}

// src/components/ArticleList.jsx
import { isEmpty } from 'lodash-es'
import React from 'react'
import { useArticlesQuery } from '../hooks'
import ArticlePreview from './ArticlePreview'

const limit = 10

function ArticleList({ filters = {}, isFeed = false }) {
  const [offset, setOffset] = React.useState(0)
  const { data, isFetching, isError, isSuccess } = useArticlesQuery({ isFeed, filters: { offset, ...filters } })

  if (isFetching) return <p className="article-preview">Loading articles...</p>
  if (isError) return <p className="article-preview">Loading articles failed :(</p>
  if (isSuccess && isEmpty(data?.articles)) return <p className="article-preview">No articles are here... yet.</p>

  return (
    <>
      {data.articles.map((article) => (
        <ArticlePreview key={article.slug} article={article} />
      ))}
      <nav>
        <ul className="pagination">
          {Array.from({ length: data.articlesCount / limit }, (_, i) => (
            <li className={offset === i ? 'page-item active' : 'page-item'} key={i}>
              <button type="button" className="page-link" onClick={() => setOffset(i)}>
                {i + 1}
              </button>
            </li>
          ))}
        </ul>
      </nav>
    </>
  )
}

export default ArticleList
