// src/components/DeleteArticleButton.vue
<script lang="ts" setup>
import { useAsyncState } from '@vueuse/core'
import api from '@/api'

const props = defineProps<{ slug: string }>()
const router = useRouter()
const { isLoading, execute: onDeleteArticle } = useAsyncState(
  async () => {
    await api.deleteArticle(props.slug)
    router.push('/')
  },
  null,
  {
    immediate: false,
  },
)
</script>

<template>
  <button
    :disabled="isLoading"
    class="btn btn-outline-danger btn-sm"
    @click="() => onDeleteArticle()"
  >
    <i class="ion-trash-a" /> Delete Article
  </button>
</template>

// src/components/DeleteArticleButton.jsx
import React from 'react'
import { useParams } from 'react-router-dom'
import { useDeleteArticleMutation } from '../hooks'

function DeleteArticleButton() {
  const { slug } = useParams()
  const { mutate, isLoading } = useDeleteArticleMutation({ slug })

  return (
    <button disabled={isLoading} onClick={() => mutate()} type="button" className="btn btn-outline-danger btn-sm">
      <i className="ion-trash-a" /> Delete Article
    </button>
  )
}

export default DeleteArticleButton
