// src/components/Article/ArticlePreview.tsx
import { For } from "solid-js";

import type { Article } from "~/types";
import NavLink from "../NavBar/NavLink";

const FAVORITED_CLASS = "btn btn-sm btn-primary";
const NOT_FAVORITED_CLASS = "btn btn-sm btn-outline-primary";

export default (props: { article: Article }) => {
  const {
    title,
    description,
    slug,
    createdAt,
    tagList,
    author: { username, image },
  } = props.article;

  return (
    <div class="article-preview">
      <div class="article-meta">
        <NavLink href={`/@${username}`} route="/profile">
          <img src={image} alt="" />
        </NavLink>

        <div class="info">
          <NavLink class="author" href={`/@${username}`} route="/profile">
            {username}
          </NavLink>
          <span
            class="date"
            textContent={/*@once*/ new Date(createdAt).toDateString()}
          />
        </div>

        {props.token && (
          <div class="pull-xs-right">
            <button
              class={
                props.article.favorited ? FAVORITED_CLASS : NOT_FAVORITED_CLASS
              }
              onClick={[props.onClickFavorite, props.article]}
            >
              <i class="ion-heart" /> {props.article.favoritesCount}
            </button>
          </div>
        )}
      </div>

      <NavLink href={`article/${slug}`} route="/article" class="preview-link">
        <h1>{title}</h1>
        <p>{description}</p>
        <span>Read more...</span>
        <ul class="tag-list">
          <For each={tagList}>
            {(tag) => (
              <li class="tag-default tag-pill tag-outline" textContent={tag} />
            )}
          </For>
        </ul>
      </NavLink>
    </div>
  );
};

// src/components/ArticlePreview/index.tsx
import dayjs from "dayjs";
import Link from "next/link";
import React from "react";
import { Article } from "types";

interface Props {
  article: Article;
}

export const ArticlePreview = ({ article }: Props) => {
  return (
    <div className="article-preview" key={article.slug}>
      <div className="article-meta">
        <Link href={`/profile/${article.slug}`}>
          <img src={article.author?.image} />
        </Link>
        <div className="info">
          <Link href="" className="author">
            {article.author?.username}
          </Link>
          <span className="date">
            {dayjs(article.createdAt).format("MMMM D, YYYY")}
          </span>
        </div>
        <button className="btn btn-outline-primary btn-sm pull-xs-right">
          <i className="ion-heart"></i> {article.favoritesCount}
        </button>
      </div>
      <Link href="" className="preview-link">
        <h1>{article.title}</h1>
        <p>{article.description}</p>
        <span>Read more...</span>
        <ul className="tag-list">
          {article.tagList.map((tag) => (
            <li className="tag-default tag-pill tag-outline" key={tag}>
              {tag}
            </li>
          ))}
        </ul>
      </Link>
    </div>
  );
};

export default ArticlePreview;
